---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/apps/controllers/api/contribucions/{id}":
    get:
      summary: Retrieves a contribution
      tags:
      - Contribucions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                required:
                - id
                - name
                - status
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                required:
                - id
                - name
                - status
        '404':
          description: pet not found
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
